### ISSUE TITLE
[Enhancement] Tag support in rare blocks/entities lists

### ISSUE THREAD

**Issue by emihead** [MagicHarp/confluence#17]
Hi, I'm not sure if this is possible but if it is then it would be a great QoL feature for modpack developers. As of now, if you have a bunch of different variants of the same ore (eg. granite, andesite, diorite iron ore, etc.) you have to add them all in manually. If there was tag support, you could just put #forge:ores/iron and be done with it. Please consider this.

**Comment by westernat** [comment]
Sure
