### ISSUE TITLE
confluence + man from the fog causing massive lag

### ISSUE THREAD

**Issue by perevozke** [MagicHarp/confluence#18]
mc version 1.20.1
forge 47.3.11
terracurio version 0.1.2
man from the fog version 1.3
when looking at water we getting a massive fps drop
![image](https://github.com/user-attachments/assets/354fdd5a-f7e0-44e6-bc0d-994218e80609)
![image](https://github.com/user-attachments/assets/0c875759-3d35-4ba9-a8f9-e38dc815788d)
causing by confluence
man from the fog CF link
https://www.curseforge.com/minecraft/mc-mods/the-man-from-the-fog

**Comment by perevozke** [comment]
is this problem possible to fix from confluence or do i need to ask curios dev?

**Comment by MagicHarp** [comment]
Our developers will get back to you tomorrow, so please be patient and thank you for your support!




无言の腹交拳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MagicHarp/confluence"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月7日(星期四) 凌晨1:08
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [MagicHarp/confluence] confluence + man from the fog causing massive lag (Issue #18)





 
is this problem possible to fix from confluence or do i need to ask curios dev?

**Comment by perevozke** [comment]
> Our developers will get back to you tomorrow, so please be patient and thank you for your support! 
as one of man from the fog discord server member said, the problem is in incompability of their mod with every mod that using dynamic render or dynamic blocks
![изображение](https://github.com/user-attachments/assets/c23b6bed-aff4-43b6-bc61-beb6cf0686e3)

**Comment by perevozke** [comment]
~~rewrote from this to this and lag is gone
i'll try to check once per second, looks like I exaggerated with once every 10 seconds~~
it lagging only if i DONT have item that allows to walk on fluid

**Comment by MagicHarp** [comment]
Try updating our cosmetic version




无言の腹交拳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MagicHarp/confluence"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月7日(星期四) 凌晨1:08
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [MagicHarp/confluence] confluence + man from the fog causing massive lag (Issue #18)





 
is this problem possible to fix from confluence or do i need to ask curios dev?

**Comment by perevozke** [comment]
not rly helped, the problem if just deleting man from the fog disappears, thanks for your help

**Comment by westernat** [comment]
I optimaized fluid walk again, what about now?
