### ISSUE TITLE
code names are buggy

### ISSUE THREAD

**Issue by VaporeonScripts** [MagicHarp/confluence#19]
neoforge 1.21.1 .79
mod version: 1.0.1
![image](https://github.com/user-attachments/assets/9e416168-681c-4849-911c-88d2f76b95a2)
![image](https://github.com/user-attachments/assets/a0e86d9d-c086-4dfb-8d32-aa5e2204c2c4)
![image](https://github.com/user-attachments/assets/8cdee340-8be8-4b4c-bf0e-b4a17ed81abf)

**Comment by westernat** [comment]
Tell me in more detail

**Comment by westernat** [comment]
oh, I see

**Comment by VaporeonScripts** [comment]
Love the mod overall

**Comment by westernat** [comment]
Have had uploads to curseforge, please waitting for review

**Comment by VaporeonScripts** [comment]
bet,ty for being so fast!
