### ISSUE TITLE
crash when clicking "q"

### ISSUE THREAD

**Issue by VaporeonScripts** [MagicHarp/confluence#20]
https://mclo.gs/nJaiAqO

**Comment by VaporeonScripts** [comment]
kinda sure its involved xd
![image](https://github.com/user-attachments/assets/169a6fa3-b62a-4cda-ae01-e55d249bea7b)

**Comment by VaporeonScripts** [comment]
(running the mod both on both client and server btw, neoforge 1.21.1 .79 ), 1.0.2

**Comment by VaporeonScripts** [comment]
1.0.1 got the same issue

**Comment by VaporeonScripts** [comment]
confirmed, removing the mod fixes the issue (mod is faulty)

**Comment by westernat** [comment]
Sorry, I made some worn code

**Comment by VaporeonScripts** [comment]
no problem, its human to make mistakes!

**Comment by westernat** [comment]
Could you please test more accessories? I'm worried that more bugs will be uploaded

**Comment by VaporeonScripts** [comment]
what do you mean "more accessories"?

**Comment by VaporeonScripts** [comment]
as of now, i tested some stuff but found no bugs, they work fine

**Comment by VaporeonScripts** [comment]
if this bug gets fixed,im adding back the mod in my modpack so i can find more bugs if those happen

**Comment by westernat** [comment]
[TerraCurio-1.0.2.zip](https://github.com/user-attachments/files/17789865/TerraCurio-1.0.2.zip)
Thanks a lot! Now I send you a fixed version, the file should unzip

**Comment by westernat** [comment]
If there is no more bug, I will upload it to curseforge

**Comment by VaporeonScripts** [comment]
alright, testing rn

**Comment by VaporeonScripts** [comment]
bug is fixed
