### ISSUE TITLE
english typo 

### ISSUE THREAD

**Issue by VaporeonScripts** [MagicHarp/confluence#22]
![image](https://github.com/user-attachments/assets/6315ae3f-e2a0-4418-89cf-ab7e06db1c13)
should be "immunity to slowness"

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/50f09f42-dd75-4c58-af81-fab3d1a4e1f4)
withering*

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/c3e65fbe-a73c-47e6-afa5-f53976396524)
Immunity to poison and withering*

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/17029bee-a358-4c3c-b362-5275ef3802f5)
slowness *
![image](https://github.com/user-attachments/assets/59d51306-9cf5-46af-8d25-1370f17d4bc3)
Grants immunity to fire and lava.* (second line)

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/0a5a2de2-5eea-418e-b428-31b000fef306)
Reduces damage taken from lava*

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/3e5ae240-0824-47ad-9c17-b629f01d41b4)
same stuff from the one before rose

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/a202f2f8-2ab2-47e0-b5cb-b42081c4cb09)
tells* (if the desc means that this item says what time it is)

**Comment by westernat** [comment]
![image](https://private-user-images.githubusercontent.com/133986238/389226390-59d51306-9cf5-46af-8d25-1370f17d4bc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDMxNjEsIm5iZiI6MTczMjUwMjg2MSwicGF0aCI6Ii8xMzM5ODYyMzgvMzg5MjI2MzkwLTU5ZDUxMzA2LTljZjUtNDZhZi04ZDI1LTEzNzBmMTdkNGJjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQwMjQ3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDllZGNjMTdmMzkzYjA4NTcwNjQ5M2M0ZDhmMmFiYmMyZGNlNmEzMzFiZDFmNmZkYWJlMjUyMTY0OWQyNDdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pZIdg2H-JGCQ1bgevFQCccH3Epq2tQjrdyuGPnWmKc4)
This is indeed only immune to fire blocks, not lava

**Comment by westernat** [comment]
![image](https://github.com/user-attachments/assets/1ec01c49-14b0-496c-a494-569e7b30aee3)
Obsidian Rose's tooltip is correct

**Comment by VaporeonScripts** [comment]
Oh,my bad then

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/bade9133-545b-41e4-a65e-e128aa60e2b1)
whats dsh?

**Comment by VaporeonScripts** [comment]
i think u meant like "sprint to dash"?

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/ea634ef2-3a78-4f4d-a095-f574b28e1390)
this doesnt really make u jump 2 times,just jump higher, please fix the desc

**Comment by BeckPhillips** [comment]
Also, the Terraspark boots say "ability t walk on water"
