### ISSUE TITLE
config option for "speed shoes" sound clientside does not work properly

### ISSUE THREAD

**Issue by BeckPhillips** [MagicHarp/confluence#24]
in the clientside config, there is an option to turn off the walking sound for "speedshoes" but when turned off, the terraspark boots still make the loud, intrusive walking/running noises.

**Comment by westernat** [comment]
Which version

**Comment by BeckPhillips** [comment]
the comment was made on Forge - game version 1.20.1, mod version 1.7, but I just updated it and it works properly!
