### ISSUE TITLE
TerraCurio Crash 

### ISSUE THREAD

**Issue by PixelPlates** [MagicHarp/confluence#4]
Hi. I am working on a rpg modpack and somehow it crash all the time when TerraCurio is installed. Without the mod there is absolutely no problem. 

I am goin to paste a crash raport. Maybe you can help me :( I really want your mod in my modpack 

https://pastebin.com/mxLW40tt

**Comment by westernat** [comment]
It looks like crushed with witcherworld mod, but this mod has not open source. May be you should report the issue to this mod
