### ISSUE TITLE
Air Hop 兼容？

### ISSUE THREAD

**Issue by DeeChael** [MagicHarp/confluence#6]
把泰拉饰品和 Air Hop 一起装了话，泰拉饰品里空气瓶等提供二段跳的饰品就不会起效果了
Air Hop：https://modrinth.com/mod/air-hop

**Comment by DeeChael** [comment]
测试了一下，实际效果其实是和 Air Hop 一起其效果导致第一次的二段跳更远了，但是实际应该产生的效果是可以再多加一次跳

**Comment by westernat** [comment]
这个bug只能等到九月份再修了
